services:
  mongo:
    image: mongo:6
    container_name: healthcare-mongo
    expose:
      - "27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - appnet
    restart: unless-stopped

  backend:
    image: ankit86/healthcare-backend:latest
    container_name: healthcare-backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/healthcare
    depends_on:
      - mongo
    networks:
      - appnet
    restart: unless-stopped

  frontend:
    image: ankit86/healthcare-frontend:latest
    container_name: healthcare-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    driver: bridge

volumes:
  mongo-data:
