services:
  mongo:
    image: mongo:6
    expose:
      - "27017"
    networks:
      - appnet

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/healthcare
    depends_on:
      - mongo
    networks:
      - appnet

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
